trigger: none
pr: none

pool: 
    vmImage: windows-latest
    
stages:
    - stage: RunNGServerAndAPITests
      displayName : "Run NG Server And Run API Test Cases"
      
      jobs:
        - job: RunNGServerAndAPITests
          displayName : "Run NG Server And Run API Test Cases"
          steps:
            - checkout: self
            - script: |
                  npm install -g json-server
                  json-server --watch ./json/db.json
            
            - task: Maven@4
              inputs:
                mavenPomFile: 'pom.xml'
                publishJUnitResults: true
                testResultsFiles: '**/surefire-reports/TEST-*.xml'
                javaHomeOption: 'JDKVersion'
                mavenVersionOption: 'Default'
                mavenAuthenticateFeed: false
                effectivePomSkip: false
                sonarQubeRunAnalysis: false
      